In [1]:
import preonpy
import numpy as np

from agent.model import Actor, Critic
from env.preon_env import *
from utils.util import *

In [2]:
env = preon_env("scene1.prscene")
state, info = env.reset()

Started simulation from frame 0 to frame 2 with 8 thread(s).
Done simulating  2  frames.


In [3]:
print(state,info)

((0.0, 12.0, 0.0, 0.0, 0.0), (468.0, 468.0, 468.0))


In [4]:
actor = Actor(5, 3, 2)
critic = Critic(5, 3, 2)

In [5]:
goal = [100.0, 0.0]    # Poured volume, spillage

In [6]:
action = actor(to_tensor(np.array([state])),to_tensor(np.array([goal])))
#action = to_numpy(action).squeeze(0)
action = to_numpy(action)
print(action)

[[ 0.18515317 -0.97661507  0.96062768]]


In [7]:
values = critic(to_tensor(np.array([state])),to_tensor(np.array([goal])),to_tensor(action))
print(values)

Variable containing:
-2.4010 -1.2800 -0.2121
[torch.FloatTensor of size 1x3]



In [17]:
np.random.normal((0.5,-0.7,0.3),0.05)

array([ 0.52138292, -0.65525076,  0.35658651])

In [21]:
np.random.random_sample()

0.3662387990162894

In [35]:
state = [0,0,15,10,50]
goal = [50,50]
a= np.absolute(np.array(state[3:5]) - np.array(goal)) - 10
a

array([ 30, -10])

In [36]:
np.maximum(a,0)

array([30,  0])